### ISSUE TITLE
Jetson xavier

### ISSUE THREAD

**Issue by duncanmix** [JetsonHacksNano/ServoKit#1]
does this work with jetson xavier?

**Comment by FPSychotic** [comment]
and Xavier NX? it is giving me errors

**Comment by mhaboali** [comment]
Yeah, Xavier Nx doesn't work for me. Any help with that?

**Comment by jakobjackson2016** [comment]
@duncanmix @FPSychotic @mhaboali Were you able to get it working with Xavier NX? Can you please share the solution with us all? Thank you!

**Comment by FPSychotic** [comment]
> @duncanmix @FPSychotic @mhaboali Were you able to get it working with Xavier NX? Can you please share the solution with us all? Thank you!

Not me, I didn't try again

**Comment by mhaboali** [comment]
Nope, I'd used the Arduino library

**Comment by andrewssobral** [comment]
Tested on my Jetson AGX Xavier and I got:
```
andrews@jetson-agx:~/Projects/jetson-hacks/ServoKit$ python3 servoPlay.py 
Initializing Servos
Initializing ServoKit
Done initializing
Traceback (most recent call last):
  File "servoPlay.py", line 39, in <module>
    with ControllerResource() as joystick:
  File "/usr/local/lib/python3.6/dist-packages/approxeng/input/selectbinder.py", line 37, in __init__
    self.discoveries = find_matching_controllers(*requirements, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/approxeng/input/controllers.py", line 192, in find_matching_controllers
    all_controllers = find_all_controllers(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/approxeng/input/controllers.py", line 268, in find_all_controllers
    id_to_constructor = get_controller_classes()
  File "/usr/local/lib/python3.6/dist-packages/approxeng/input/controllers.py", line 246, in get_controller_classes
    controllers = {key: value for key, value in built_in_classes()}
  File "/usr/local/lib/python3.6/dist-packages/approxeng/input/controllers.py", line 246, in <dictcomp>
    controllers = {key: value for key, value in built_in_classes()}
  File "/usr/local/lib/python3.6/dist-packages/approxeng/input/controllers.py", line 218, in built_in_classes
    for vendor_id, product_id in controller_class.registration_ids():
TypeError: 'NoneType' object is not iterable
Exiting... 
Cleaning up pins
andrews@jetson-agx:~/Projects/jetson-hacks/ServoKit$
```
Someone knows how to fix it?
