### ISSUE TITLE
[BUG] Unable to run the script ./installServoKit.sh 

### ISSUE THREAD

**Issue by SYTECH27** [JetsonHacksNano/ServoKit#7]
**Describe the issue**
Describe the issue that you are having. 

Using cached https://files.pythonhosted.org/packages/a2/65/5da8d1d4a22701fedf9dbae9094e40185d58be25b86175eb0861d55398a5/adafruit-circuitpython-servokit-1.3.10.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-djyjfkka/adafruit-circuitpython-servokit/setup.py", line 61, in <module>
        py_modules=["adafruit_servokit"],
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 372, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 528, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
        return self.resolve()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pip-build-djyjfkka/adafruit-circuitpython-servokit/.eggs/setuptools_scm-7.0.4-py3.6.egg/setuptools_scm/__init__.py", line 5
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-djyjfkka/adafruit-circuitpython-servokit/

**NVIDIA Jetson Hardware**
- [ X] Jetson TX1
Other: 

**L4T / JetPack Version**
Which version of L4T/JetPack are you using? 

Package: nvidia-jetpack
Version: 4.6-b199
Architecture: arm64
Maintainer: NVIDIA Corporation
Installed-Size: 194

** Software version**
Python 3.6.9. Additional software details are listed in the last section. 

**To Reproduce**
For example, what command line did you run?
Download and run ./installServoKit.sh

**Expected behavior**
The software is supposed to install servo kit on Jetson TX1. But the errors thrown prevent that. 

**Additional context**
python3 --version
Python 3.6.9

pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

pip3 list --format=columns
Package                       Version            
----------------------------- -------------------
apturl                        0.5.2              
asn1crypto                    0.24.0             
beautifulsoup4                4.6.0              
blinker                       1.4                
Brlapi                        0.6.6              
certifi                       2018.1.18          
chardet                       3.0.4              
click                         6.7                
colorama                      0.3.7              
cryptography                  2.1.4              
cupshelpers                   1.0                
cycler                        0.10.0             
decorator                     4.1.2              
defer                         1.0.6              
distro-info                   0.18ubuntu0.18.04.1
ez-setup                      0.9                
feedparser                    5.2.1              
html5lib                      0.999999999        
httplib2                      0.9.2              
idna                          2.6                
Jetson.GPIO                   2.0.17             
keyring                       10.6.0             
keyrings.alt                  3.0                
language-selector             0.1                
launchpadlib                  1.10.6             
lazr.restfulclient            0.13.5             
lazr.uri                      1.0.3              
louis                         3.5.0              
lxml                          4.2.1              
macaroonbakery                1.1.3              
Mako                          1.0.7              
MarkupSafe                    1.0                
matplotlib                    2.1.1              
numpy                         1.13.3             
oauth                         1.0.1              
oauthlib                      2.0.6              
onboard                       1.4.1              
pandas                        0.22.0             
pip                           9.0.1              
protobuf                      3.0.0              
pycairo                       1.16.2             
pycrypto                      2.6.1              
pycups                        1.9.73             
pygobject                     3.26.1             
PyJWT                         1.5.3              
pymacaroons                   0.13.0             
PyNaCl                        1.1.2              
pyparsing                     2.2.0              
pyRFC3339                     1.0                
python-apt                    1.6.5+ubuntu0.7    
python-dateutil               2.6.1              
python-debian                 0.1.32             
pytz                          2018.3             
pyxattr                       0.6.0              
pyxdg                         0.25               
PyYAML                        3.12               
requests                      2.18.4             
requests-unixsocket           0.1.5              
scipy                         0.19.1             
SecretStorage                 2.3.1              
setuptools                    39.0.1             
simplejson                    3.13.2             
six                           1.11.0             
ssh-import-id                 5.7                
system-service                0.3                
systemd-python                234                
ubuntu-drivers-common         0.0.0              
unity-scope-calculator        0.1                
unity-scope-chromiumbookmarks 0.1                
unity-scope-colourlovers      0.1                
unity-scope-devhelp           0.1                
unity-scope-firefoxbookmarks  0.1                
unity-scope-manpages          0.1                
unity-scope-openclipart       0.1                
unity-scope-texdoc            0.1                
unity-scope-tomboy            0.1                
unity-scope-virtualbox        0.1                
unity-scope-yelp              0.1                
unity-scope-zotero            0.1                
urllib3                       1.22               
urwid                         2.0.1              
wadllib                       1.3.2              
webencodings                  0.5                
wheel                         0.30.0             
xkit                          0.0.0              
youtube-dl                    2018.3.14          
zope.interface                4.3.2

**Comment by belal-ibrahim** [comment]
pip3 install --upgrade setuptools
 would solve your issue

**Comment by belal-ibrahim** [comment]
then use this commands 
sudo pip3 install -U \
adafruit-circuitpython-busdevice==5.1.2 \
adafruit-circuitpython-motor==3.3.5 \
adafruit-circuitpython-pca9685==3.4.1 \
adafruit-circuitpython-register==1.9.8 \
adafruit-circuitpython-servokit==1.3.8 \
Adafruit-Blinka==6.11.1 \
Adafruit-GPIO==1.0.3 \
Adafruit-MotorHAT==1.4.0 \
Adafruit-PlatformDetect==3.19.6 \
Adafruit-PureIO==1.1.9 \
Adafruit-SSD1306==1.6.2

**Comment by SYTECH27** [comment]
Hi Belal,

I ran the following command:
pip3 install --upgrade setuptools

and then the following commands

sudo -H pip3 install -U adafruit-circuitpython-busdevice==5.1.2 
sudo -H pip3 install -U adafruit-circuitpython-motor==3.3.5
sudo -H pip3 install -U adafruit-circuitpython-pca9685==3.4.1
sudo -H pip3 install -U adafruit-circuitpython-register==1.9.8
sudo -H pip3 install -U adafruit-circuitpython-servokit==1.3.8
sudo -H pip3 install -U Adafruit-Blinka==6.11.1
sudo -H pip3 install -U Adafruit-GPIO==1.0.3
sudo -H pip3 install -U Adafruit-MotorHAT==1.4.0
sudo -H pip3 install -U Adafruit-PlatformDetect==3.19.6
sudo -H pip3 install -U Adafruit-PureIO==1.1.9
sudo -H pip3 install -U Adafruit-SSD1306==1.6.2

After all of that I ran the command

. ./installServoKit.sh 
The result is:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.5).
0 upgraded, 0 newly installed, 0 to remove and 97 not upgraded.
Collecting adafruit-circuitpython-servokit
  Using cached https://files.pythonhosted.org/packages/a2/65/5da8d1d4a22701fedf9dbae9094e40185d58be25b86175eb0861d55398a5/adafruit-circuitpython-servokit-1.3.10.tar.gz
Collecting Adafruit-Blinka>=7.0.0 (from adafruit-circuitpython-servokit)
  Could not find a version that satisfies the requirement Adafruit-Blinka>=7.0.0 (from adafruit-circuitpython-servokit) (from versions: 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 1.0.2, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 3.3.10, 3.4.0, 3.4.1, 3.5.0, 3.5.1, 3.5.2, 3.6.0, 3.6.1, 3.7.0, 3.7.1, 3.8.0, 3.9.0, 3.10.0, 4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.4.0, 4.5.0, 4.6.0, 4.7.0, 4.8.0, 4.8.1, 4.9.0, 4.10.0, 4.10.1, 5.0.0, 5.0.1, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.2.3, 5.2.4, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.4.0, 5.4.1, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4, 5.6.0, 5.7.0, 5.8.0, 5.8.1, 5.8.2, 5.9.0, 5.9.1, 5.9.2, 5.10.0, 5.11.0, 5.12.0, 5.13.0, 5.13.1, 6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.2.0, 6.2.1, 6.2.2, 6.3.0, 6.3.1, 6.3.2, 6.4.0, 6.4.1, 6.4.2, 6.5.0, 6.6.0, 6.6.1, 6.6.2, 6.7.0, 6.8.0, 6.8.1, 6.8.2, 6.8.3, 6.9.0, 6.9.1, 6.9.2, 6.10.0, 6.10.1, 6.10.2, 6.10.3, 6.11.0, 6.11.1, 6.12.0, 6.13.0, 6.13.1, 6.14.0, 6.14.1, 6.15.0)
No matching distribution found for Adafruit-Blinka>=7.0.0 (from adafruit-circuitpython-servokit)

I am not sure what script is trying to get an unavailable version of Adafruit-Blinka. 

Please help. 

Thank you

**Comment by belal-ibrahim** [comment]
I think you need to upgrade pip3 version,
`pip3 install --upgrade pip`

**Comment by imadjawad** [comment]
Belal you solved my problem Man, Thank you!
